name: Testando o Trigger do tipo delete

on:
    delete

jobs:
    print-branch-or-tag-creation:
        runs-on: ubuntu-latest
        steps:
            - name: Aviso sobre a criação da branch ou tag
              run: echo "Uma nova branch ou tag foi deletada no repositório"