name: Criando nosso Trigger discussion

on:
    discussion:
        types: [created, edited, answered]

jobs:
    job-discussion:
        runs-on: ubuntu-latest
        steps:
            - name: Printa discussion
              run: echo "Esse job foi triggado por um discussion criada/alterada/respondida"