name: Criando nosso Trigger Schedule

on:
    schedule:
        - cron: 59 19 * * 0
        - cron: '*/5 * * * 0'

jobs:
    executa-schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Horário agendado
              if: github.event.schedule == '59 19 * * 0'
              run: echo "Esse step rodou pois essa execução foi pelo horário agendado"

            - name: Informa horário
              run: echo "Nesse step, passam todos os cron. Agora são $(date) UTC"